import { COMMON_MESSAGES } from '../../shared/constants/messages';
import { ENTITY_MESSAGES, ENTITY_SUCCESS, ENTITY_VALIDATION } from '../../shared/constants/entity-messages';

export const LESSON_MESSAGES = {
  VALIDATION: {
    ...COMMON_MESSAGES.VALIDATION,
    TITLE_REQUIRED: ENTITY_VALIDATION.FIELD_REQUIRED('Название', 'урока'),
    TITLE_TOO_LONG: ENTITY_VALIDATION.FIELD_TOO_LONG('Название', 'урока', 100),
    DESCRIPTION_REQUIRED: ENTITY_VALIDATION.FIELD_REQUIRED('Описание', 'урока'),
    DESCRIPTION_TOO_SHORT: ENTITY_VALIDATION.FIELD_TOO_SHORT('Описание', 'урока', 10),
    DESCRIPTION_TOO_LONG: ENTITY_VALIDATION.FIELD_TOO_LONG('Описание', 'урока', 2000),
    ORDER_REQUIRED: 'Порядковый номер обязателен',
    ORDER_MIN: 'Порядковый номер должен быть не менее 1',
    INPUT_EXAMPLES_TOO_LONG: 'Примеры входных данных не должны превышать 1000 символов',
    OUTPUT_EXAMPLES_TOO_LONG: 'Примеры выходных данных не должны превышать 1000 символов',
    FILE_TYPE_REQUIRED: 'Тип файла обязателен',
    FILE_TYPE_INVALID: 'Тип файла должен быть video или resource',
    FILE_TITLE_REQUIRED: 'Название файла обязательно',
    FILE_TITLE_TOO_LONG: 'Название файла не должно превышать 100 символов',
    FILE_DESCRIPTION_TOO_LONG: 'Описание файла не должно превышать 500 символов',
    FILE_URL_REQUIRED: 'URL файла обязателен',
    RESOURCE_INDEX_INVALID: 'Индекс ресурса должен быть числом',
  },
  ERROR: {
    ...COMMON_MESSAGES.ERROR,
    NOT_FOUND: ENTITY_MESSAGES.NOT_FOUND('Урок'),
    ALREADY_EXISTS: ENTITY_MESSAGES.ALREADY_EXISTS('Урок с таким названием'),
    ACCESS_DENIED: ENTITY_MESSAGES.ACCESS_DENIED('уроку'),
    INVALID_LESSON_ID: 'Некорректный ID урока',
    INVALID_COURSE_ID: 'Некорректный ID курса',
    FILE_NOT_UPLOADED: 'Файл не загружен',
  },
  SUCCESS: {
    LESSON_CREATED: ENTITY_SUCCESS.CREATED('Урок'),
    LESSON_UPDATED: ENTITY_SUCCESS.UPDATED('Урок'),
    LESSON_DELETED: ENTITY_SUCCESS.DELETED('Урок'),
    FILE_UPLOADED: 'Файл успешно загружен',
    FILE_DELETED: 'Файл успешно удален',
    RESOURCE_DELETED: ENTITY_SUCCESS.DELETED('Ресурс'),
    ACCESS_GRANTED: 'Доступ к уроку предоставлен',
  },
  LOGS: {
    FILE_RECEIVED: 'Получен файл через multer:',
    FILE_PROCESSED: 'Файл обработан:',
    CLEANUP_STARTED: 'Начало очистки файлов урока из S3',
    CLEANUP_COMPLETED: 'Файлы урока успешно удалены из S3',
    CLEANUP_ERROR: 'Ошибка при удалении файлов урока из S3:',
    VIDEO_REPLACED: 'Замена видео для урока',
    VIDEO_ADDED: 'Добавление видео для урока',
    OLD_VIDEO_DELETED: 'Старое видео удалено:',
    OLD_VIDEO_DELETE_ERROR: 'Ошибка при удалении старого видео:',
    RESOURCE_REPLACED: 'Замена существующего ресурса:',
    RESOURCE_ADDED: 'Добавление нового ресурса:',
    OLD_RESOURCE_DELETED: 'Старый файл ресурса удален:',
    OLD_RESOURCE_DELETE_ERROR: 'Ошибка при удалении старого файла ресурса:',
    RESOURCE_FILE_DELETED: 'Файл ресурса удален:',
    RESOURCE_DELETE_ERROR: 'Ошибка при удалении файла из хранилища:',
  },
} as const;
